# how to skip Circle builds with a commit message: https://circleci.com/docs/2.0/skip-build/
version: 2 # use CircleCI 2.0
workflows:
  version: 2
  test:
    jobs:
      - test
  deploy:
    jobs:
      - build_and_deploy:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs: # A basic unit of work in a run
  build_and_deploy:
    working_directory: ~/html2ans
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = arcpsteam" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Build and deploy
          command: |
            python3 -m virtualenv html2ans
            source html2ans/bin/activate
            python setup.py install test verify sdist bdist_wheel build_sphinx
            twine upload dist/*
  test:
    working_directory: ~/html2ans
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: themattrix/tox # https://github.com/themattrix/docker-tox
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Run tests
          command: tox -e circleci
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-reports
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-reports
